//created on: 2015-7-7
package rule.discovery.article

//list any import classes here.

import com.wonders.xlab.healthcloud.service.drools.discovery.article.input.HealthInfoClickSample;

import com.wonders.xlab.healthcloud.utils.DateUtils;
import java.util.Date;
import java.util.HashMap;
import java.lang.Math;

/**
 * 计算两个日期的间隔天数。
 */
function Integer aritcle_perior_days(Date fromDate, Date toDate) {
	return DateUtils.calculatePeiorDaysOfTwoDate(fromDate, toDate);
}

//declare any global variables here

global Double clickCount_X; // 这个值是全局配置的，由外面传入
global HashMap clickCountOutputMap; // key=文章id，value=OutputHealthInfoClickCount

// 按照公式计算文章点击次数
rule "calcu healthinfo clickCount"
	when
		HealthInfoClickSample ( 
			$id : healInfoSample.healthInfoId, 
			$createTime : healInfoSample.createTime, 
			$clickCount : healInfoSample.clickCount,
			$clickCount_A : healInfoSample.clickCount_A 
		)
	then
		// 当前时间间隔文章创建时间天数
		int n = aritcle_perior_days($createTime, new Date());
		// 公式 A+(1+X)^n*B
		Double new_click_count = $clickCount_A * Math.pow((1 + clickCount_X), n) + $clickCount;
		clickCountOutputMap.put($id, Math.round(new_click_count));
end

